url: "https://blog.vcz.fr"
title: "VCZ Blog"
description: "Simplicity-powered blog from Vincenzo Scalzi - Web Performance Addict && Engineer"

excerpt_separator: "<!-- READ MORE -->"
paginate: 10
paginate_path: "/all/:num"

author:
  name: Vincenzo Scalzi
  display_name: VCZ
  web: https://vcz.fr
  twitter:
    username: vcz_fr
    card: summary
  github: vcz-fr

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  highlighter: rouge

defaults:
  - scope:
      path: _posts
    values:
      layout: blog

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate